# 유기동물 추천 프로젝트

Kaggle https://www.kaggle.com/aaronschlegel/austin-animal-center-shelter-intakes-and-outcomes

---
## 문제 정의
동물들의 데이터를 기반으로 오스틴 애니멀 센터에서 입양을 고려하는 나에게 맞는 동물을 찾아보자

## 가설
데이터를 통해 어떤 동물을 입양하면 좋을 지 판단할 수 있다.

## 목표
동물들의 특징 데이터를 입력받아 입양을 고려하는 나에게 맞는 동물을 선택할 수 있다.

-----
# 분석 단계
## 단계 1) 데이터를 불러온다
## 단계 2) EDA & Feature Engineering
## 단계 3) 데이터셋을 구성
## 단계 4) 모델링하고 학습 진행
## 단계 5) 모델을 검증

---
# 1. 데이터 불러오기

In [3]:
import pandas as pd

df = pd.read_csv('data/dogs.csv')
df

,age_upon_intake,animal_id,animal_type,breed,color,datetime,datetime2,found_location,intake_condition,intake_type,name,sex_upon_intake
0,8 years,A706918,Dog,English Springer Spaniel,White/Liver,2015-07-05T12:59:00.000,2015-07-05T12:59:00.000,9409 Bluegrass Dr in Austin (TX),Normal,Stray,Belle,Spayed Female
1,11 months,A724273,Dog,Basenji Mix,Sable/White,2016-04-14T18:43:00.000,2016-04-14T18:43:00.000,2818 Palomino Trail in Austin (TX),Normal,Stray,Runster,Intact Male
2,4 weeks,A665644,Cat,Domestic Shorthair Mix,Calico,2013-10-21T07:59:00.000,2013-10-21T07:59:00.000,Austin (TX),Sick,Stray,NaN,Intact Female
3,4 years,A682524,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2014-06-29T10:38:00.000,2014-06-29T10:38:00.000,800 Grove Blvd in Austin (TX),Normal,Stray,Rio,Neutered Male
4,2 years,A743852,Dog,Labrador Retriever Mix,Chocolate,2017-02-18T12:46:00.000,2017-02-18T12:46:00.000,Austin (TX),Normal,Owner Surrender,Odin,Neutered Male
...,...,...,...,...,...,...,...,...,...,...,...,...
80182,10 years,A769067,Dog,Boxer Mix,Brown Brindle,2018-03-29T18:20:00.000,2018-03-29T18:20:00.000,11216 Jollyville Rd 216 in Austin (TX),Aged,Stray,NaN,Spayed Female
80183,5 years,A768934,Dog,Dachshund Wirehair/Chihuahua Shorthair,Chocolate/White,2018-03-27T14:27:00.000,2018-03-27T14:27:00.000,603 West Johanna Street in Austin (TX),Normal,Stray,NaN,Intact Male
80184,2 years,A769064,Other,Bat Mix,Brown,2018-03-29T17:13:00.000,2018-03-29T17:13:00.000,2519 Scarbrough Dr in Travis (TX),Normal,Wildlife,NaN,Unknown
80185,3 years,A675680,Dog,German Shepherd/Black/Tan Hound,Black/Brown,2014-03-31T18:10:00.000,2014-03-31T18:10:00.000,Austin (TX),Normal,Public Assist,Draco,Neutered Male
80186,1 year,A680949,Dog,Chihuahua Shorthair/Beagle,Tan,2014-06-10T11:53:00.000,2014-06-10T11:53:00.000,4605 Lyra Cir in Austin (TX),Normal,Stray,Lolo,Intact Male

In [4]:
df.describe()

,age_upon_intake,animal_id,animal_type,breed,color,datetime,datetime2,found_location,intake_condition,intake_type,name,sex_upon_intake
count,80187,80187,80187,80187,80187,80187,80187,80187,80187,80187,55603,80186
unique,46,72365,5,2166,529,57055,57055,36772,8,5,14731,5
top,1 year,A721033,Dog,Domestic Shorthair Mix,Black/White,2016-09-23T12:00:00.000,2016-09-23T12:00:00.000,Austin (TX),Normal,Stray,Bella,Intact Male
freq,14672,13,45743,23519,8340,64,64,14443,70520,56280,357,25488

---
# 2. EDA & Feature Engineering

In [5]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

## 필요없는 요소 제거