In [1]:
import pandas as pd

df = pd.read_csv('data/iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [2]:
input_data = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
target_data = df['Species']

In [3]:
input_data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [6]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(input_data, target_data)

x_train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
45             4.8           3.0            1.4           0.3
74             6.4           2.9            4.3           1.3
95             5.7           3.0            4.2           1.2
86             6.7           3.1            4.7           1.5
51             6.4           3.2            4.5           1.5
..             ...           ...            ...           ...
46             5.1           3.8            1.6           0.2
128            6.4           2.8            5.6           2.1
133            6.3           2.8            5.1           1.5
81             5.5           2.4            3.7           1.0
4              5.0           3.6            1.4           0.2

[112 rows x 4 columns]

In [10]:
y_test.count()

38

In [11]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()
tree.fit(x_train, y_train)

print('training set accuracy: ', tree.score(x_train, y_train))
print('test set accuracy: ', tree.score(x_test, y_test))

training set accuracy:  1.0
test set accuracy:  0.9736842105263158

In [12]:
prediction = tree.predict(x_test)
prediction

array(['Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor'], dtype=object)

In [13]:
x_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
98             5.1           2.5            3.0           1.1
145            6.7           3.0            5.2           2.3
88             5.6           3.0            4.1           1.3
0              5.1           3.5            1.4           0.2
14             5.8           4.0            1.2           0.2
49             5.0           3.3            1.4           0.2
76             6.8           2.8            4.8           1.4
25             5.0           3.0            1.6           0.2
77             6.7           3.0            5.0           1.7
85             6.0           3.4            4.5           1.6
24             4.8           3.4            1.9           0.2
121            5.6           2.8            4.9           2.0
55             5.7           2.8            4.5           1.3
7              5.0           3.4            1.5           0.2
28             5.2           3.4            1.4           0.2
103            6.3           2.9            5.6           1.8
66             5.6           3.0            4.5           1.5
17             5.1           3.5            1.4           0.3
109            7.2           3.6            6.1           2.5
56             6.3           3.3            4.7           1.6
112            6.8           3.0            5.5           2.1
102            7.1           3.0            5.9           2.1
9              4.9           3.1            1.5           0.1
96             5.7           2.9            4.2           1.3
126            6.2           2.8            4.8           1.8
75             6.6           3.0            4.4           1.4
22             4.6           3.6            1.0           0.2
10             5.4           3.7            1.5           0.2
110            6.5           3.2            5.1           2.0
114            5.8           2.8            5.1           2.4
120            6.9           3.2            5.7           2.3
1              4.9           3.0            1.4           0.2
42             4.4           3.2            1.3           0.2
84             5.4           3.0            4.5           1.5
40             5.0           3.5            1.3           0.3
15             5.7           4.4            1.5           0.4
35             5.0           3.2            1.2           0.2
57             4.9           2.4            3.3           1.0

In [15]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(n_estimators = 100)
forest.fit(x_train, y_train)

print('training set accuracy: ', forest.score(x_train, y_train))
print('test set accuracy: ', forest.score(x_test, y_test))

prediction_by_forest = forest.predict(x_test)
prediction_by_forest

training set accuracy:  1.0
test set accuracy:  0.9736842105263158

array(['Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor'], dtype=object)